### ISSUE TITLE
Does esserializer supports Circular structures?

### ISSUE THREAD

**Issue by Judahh** [shaochuancs/esserializer#19]
Does esserializer supports Circular structures? 
It has mongoose connections instances, circular dependancies, and a map to binded functions used by a pub/sub pattern structure.
I've tryed using esserializer on complex Circular structures, and received this error:
```
RangeError: Maximum call stack size exceeded
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:291)
    at /Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:373
    at Array.map (<anonymous>)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:347)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:441)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:441)
    at /Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:373
    at Array.map (<anonymous>)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:347)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:441)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:441)
    at /Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:373
    at Array.map (<anonymous>)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:347)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:441)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:441)
    at /Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:373
    at Array.map (<anonymous>)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:347)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:441)
    at Function.r.getSerializeValueWithClassName (/Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:441)
    at /Users/judah/auth/node_modules/esserializer/dist/bundle.js:1:373
(node:8870) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
```

**Comment by shaochuancs** [comment]
Thanks Judahh for your feedback. I'm trying to add circular structure support and hope it can be delivered in version 1.1

**Comment by shaochuancs** [comment]
Circular structure support has been added in ESSerializer Pro v1.1.0 now
